version: '3'
networks:
  krakend-net:
    driver: bridge
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - krakend-net

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - krakend-net
  # KrakenD API Gateway
  krakend:
    image: devopsfaith/krakend:latest
    #container_name: krakend
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - "8000:8000"
    restart: always
    networks:
      - krakend-net
    depends_on:
      - rental-room-service
    environment:
      - KRAKEND_PORT=8000
  # Rental Room Service
  rental-room-service:
    build:
      context: .
      dockerfile: ./rental-room-service/Dockerfile
    #container_name: rental-room-service
    ports:
      - "8081:8081"
    restart: always
    networks:
      - krakend-net
    depends_on:
      - kafka
    env_file:
      - ./services.env
  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    #container_name: payment-service
    ports:
      - "8083:8083"
    restart: always
    networks:
      - krakend-net
    depends_on:
      - kafka
      - zookeeper
    env_file:
      - ./services.env
  listing-service:
    build:
      context: .
      dockerfile: ./listing-service/Dockerfile
    #container_name: listing-service
    ports:
      - "8082:8082"
    restart: "always"
    networks:
      - krakend-net
    depends_on:
      - kafka
    env_file:
      - ./services.env
  rating-service:
    build:
      context: .
      dockerfile: ./rating-service/Dockerfile
    #container_name: rating-service
    ports:
      - "8085:8085"
    restart: always
    networks:
      - krakend-net
    depends_on:
      - kafka
    env_file:
      - ./services.env
  complaint-service:
    build:
      context: .
      dockerfile: ./complaint-service/Dockerfile
    #container_name: complaint-service
    ports:
      - "8086:8086"
    restart: "always"
    networks:
      - krakend-net
    depends_on:
      - kafka
    env_file:
      - ./services.env
  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    #container_name: notification-service
    ports:
      - "8087:8087"
    restart: "always"
    networks:
      - krakend-net
    depends_on:
      - kafka
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    # container_name: auth-service
    ports:
      - "8084:8084"
    restart: "always"
    env_file:
      - ./auth-service/auth.env
    networks:
      - krakend-net